# Generated by Django 5.1 on 2024-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('proxy_url', models.CharField(max_length=256)),
                ('proxy_user', models.CharField(blank=True, max_length=256, null=True)),
                (
                    'proxy_password',
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ('backend_name', models.CharField(max_length=16)),
                ('backend_server_name', models.CharField(max_length=64, unique=True)),
                ('backend_server_state', models.IntegerField(default=-1)),
            ],
        ),
    ]
