# Generated by Django 5.1.2 on 2024-11-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statectl', '0002_rename_server_statectlserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='statectlserver',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
    ]
